### ISSUE TITLE
After installing the package on the machine, do we need to compile?

### ISSUE THREAD

**Issue by syang** [Bigjango13/MCPI-Addons#4]
The Readme seems not clear. Could you please make it a bit clearer?

`Just run ./build.sh to create the bianary and run mv libextrapi.so ~/.minecraft-pi/mods to install it.`

Why do we need the above step? 
Note: I have successfully installed the python package `pip3 install mcpi-addons`

**Comment by Bigjango13** [comment]
Should be fixed in 84da3b7 :+1:

**Comment by syang** [comment]
@Bigjango13 I am still not 100% sure if I need to do the ‘compiling’ step after I do pip install. Can you clarify when you put the build.sh there?

**Comment by Bigjango13** [comment]
I'm not sure what you mean, what part is confusing? It's needed to compile the backend which is loaded as a MCPI-Reborn mod.

**Comment by syang** [comment]
> I'm not sure what you mean, what part is confusing? It's needed to compile the backend which is loaded as a MCPI-Reborn mod.

I guess I did not follow the following step (also please see issue #5 -- that's what I experienced)

```
Just run ./build.sh to create the binary and run mv libextrapi.so ~/.minecraft-pi/mods to install the mod, this is needed because MCPI doesn't support any of these extentions that this api adds, so a C++ mod is loaded to intercept CommandServer::parse.
```

I am running this on my Macbook, and I am trying to use Python to modify my server. Your compiling step seems to only target Raspberry Pi (Linux), can you give guidance on the Macbook?

**Comment by Bigjango13** [comment]
> I am running this on my Macbook, and I am trying to use Python to modify my server.

This mod is only for [Minecraft Pi: Reborn](https://github.com/MCPI-Revival/minecraft-pi-reborn) and not the Java/Bedrock/Any other editions. However, if you want use python to control your Java server you might be able to use [RaspberryJuice](https://github.com/zhuowei/RaspberryJuice)

The reason I only provide a way to build on Linux is because Minecraft Pi: Reborn only supports Linux.
